version: '3.7'

services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: 'budget'
    hostname: 'budget'
    user: 1000:1000
    read_only: true
    ports:
      - '5006:5006'
    environment:
      # Sync your bank account: https://nordigen.com/en/
      # - ACTUAL_NORDIGEN_SECRET_ID=xxxx
      # - ACTUAL_NORDIGEN_SECRET_KEY=xxxx
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    volumes:
      - ./actual-data:/data
    restart: always
security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
